### PR TITLE
Handle EE folder creation errors and Firestore errors in disaster creation

### LINKED ISSUE #331: Display error when EE folder fails to be created during manage_disaster add

### PR DESCRIPTION
**Pull request by janakdr**
We just show a snackbar error. Not sure there's more we can do, because it's unexpected.

This will slightly slow down creation, because it's EE then Firestore, but worth it.

Also fix slightly broken test: under the covers we were creating states for the letters in 'IG, MY' because inputs can't have array values.

Closes #331

### CODE REVIEW

File: docs/import/manage_disaster.js [hunk 1]
```diff
@@ -369,71 +370,67 @@ function addDisaster() {
...
-    folderCreationPromises.push(
-        getCreateFolderPromise(legacyStateDir + '/' + state));
+  const eeFolderPromises =
+      [getCreateFolderPromise(eeLegacyPathPrefix + disasterId)];
+  states.forEach(
+      (state) => eeFolderPromises.push(
+          getCreateFolderPromise(legacyStateDir + '/' + state)));
+
+  const tailError = '" You can try refreshing the page';
+  // Unsafe to do the Firestore write before EE folders are created, since maybe
```
Comment (juliexxia) [inline docs/import/manage_disaster.js]: super nit: I get this phrasing knowing the history of this method but maybe just say the affirmative i.e. "wait on ee folder creation to do firestore write because..."

File: docs/import/manage_disaster.js [hunk 2]
```diff
@@ -369,71 +370,67 @@ function addDisaster() {
...
-    });
-    if (!added) disasterPicker.append(createOptionFrom(disasterId));
-    toggleState(true);
-
-    disasterPicker.val(disasterId).trigger('change');
+  try {
+    await disasterCollectionReference().doc(disasterId).set(currentData);
+  } catch (err) {
+    const message = err.message ? err.message : err;
+    showError('Error writing to Firestore: "' + message + tailError);
```
Comment (juliexxia) [inline docs/import/manage_disaster.js]: Should we do this here if we're not doing it everywhere?

File: docs/import/manage_disaster.js [hunk 3]
```diff
@@ -369,71 +370,67 @@ function addDisaster() {
...
+    return false;
+  }
+  const disasterPicker = $('#disaster-dropdown');
+  const disasterOptions = disasterPicker.children();
+  let added = false;
+  // We expect this recently created disaster to go near the top of the list, so
+  // do a linear scan down.
+  // Note: let's hope this tool isn't being used in the year 10000.
+  // Comment needed to quiet eslint.
+  disasterOptions.each(/* @this HTMLElement */ function() {
```
Comment (juliexxia) [inline docs/import/manage_disaster.js]: nit: could inline disasterPicker.children() creation here and not create disasterOptions

File: docs/import/manage_disaster.js [hunk 4]
```diff
@@ -369,71 +370,67 @@ function addDisaster() {
  * Writes the given details to a new disaster entry in firestore. Fails if
  * there is an existing disaster with the same details.
  *
```
Comment (juliexxia) [inline docs/import/manage_disaster.js]: maybe add comment detail about printing error since we removed from below?

File: cypress/integration/unit_tests/manage_disaster_add_delete_test.js [hunk 5]
```diff
@@ -135,10 +150,64 @@ describe('Add/delete-related tests for manage_disaster.js', () => {
...
+    return $(document.createElement('option')).val(text).prop('selected', true);
+  }
+
+  it('Error creating EE folder', () => {
+    const id = '2005-summer';
+    const states = [KNOWN_STATE];
+    const errorStub = cy.stub(ErrorLib, 'showError');
+    // Tests don't have permission to create folders, so this will exercise EE
+    // failure mode better than we could fake it.
+    createFolderStub.restore();
```
Comment (juliexxia) [inline cypress/integration/unit_tests/manage_disaster_add_delete_test.js]: why do you need to restore here?

Comment (janakdr) [reply cypress/integration/unit_tests/manage_disaster_add_delete_test.js]: Because it was stubbed in the beforeEach. Expanded comment.

File: docs/import/manage_disaster.js (hunk 1 above)
Comment (janakdr) [reply docs/import/manage_disaster.js]: Rephrased, how's this?

File: docs/import/manage_disaster.js (hunk 2 above)
Comment (janakdr) [reply docs/import/manage_disaster.js]: perfect enemy of the good? This seems better than the prior state, and I don't think it will share code with the other write, if we do add error handling there.

File: docs/import/manage_disaster.js (hunk 4 above)
Comment (janakdr) [reply docs/import/manage_disaster.js]: Not sure I understand. Saying here that this function now shows errors on failure? Added a couple of lines. Note that the prior comment, about not being the gd user, is no longer relevant since only the gd user can access this page.

File: cypress/integration/unit_tests/manage_disaster_add_delete_test.js (hunk 5 above)
Comment (juliexxia) [reply cypress/integration/unit_tests/manage_disaster_add_delete_test.js]: Ah sorry got this mixed up with resetHistory
